[production]
# General
# -----------------------------------------------------------------------------
DEBUG = false

ALLOWED_HOSTS = []


# Email
# -----------------------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_TIMEOUT = 5



[development]
# General
# -----------------------------------------------------------------------------
DEBUG = true

ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1"]

# Applications
# -----------------------------------------------------------------------------
# https://django-extensions.readthedocs.io/en/latest/
INSTALLED_APPS = ["django_extensions", 'dynaconf_merge']




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'

# Email
# -----------------------------------------------------------------------------
# Определяет класс используемый для отправки email.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'