"""
Django settings for bookmarks project.

Generated by 'cookiecutter'
https://github.com/cookiecutter/cookiecutter
from 'cookiecutter-django2-simpliest' template
https://github.com/mk-dv/cookiecutter-django-2-simpliest/
using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from pathlib import Path

import dynaconf

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).parents[2]

# APPLICATION DEFINITION
# -----------------------------------------------------------------------------

# Django searches all applications for templates in turn. When redefining login
# or logout templates, the first one that is encountered will be used,
# therefore the application with the redefined templates must be before
# `django.contrib.admin` app.
LOCAL_APPS = [
    'bookmarks.apps.account.apps.AccountConfig',
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = []

# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = LOCAL_APPS + DJANGO_APPS + THIRD_PARTY_APPS

# MIDDLEWARE
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/dev/ref/settings/#middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URLS
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/dev/ref/settings/#root-urlconf
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# https://docs.djangoproject.com/en/dev/ref/settings/#wsgi-application
WSGI_APPLICATION = 'config.wsgi.application'

# PASSWORD VALIDATION
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# LOG-IN
# -----------------------------------------------------------------------------

# The URL or named URL-pattern where django will redirect the user upon
# successful authorization.
# https://docs.djangoproject.com/en/2.2/ref/settings/#login-redirect-url
LOGIN_REDIRECT_URL = 'dashboard'

# The URL or named URL pattern where requests are redirected for login when
#  using the login_required() decorator, LoginRequiredMixin, or AccessMixin.
LOGIN_URL = 'login'

# The address by clicking on which the user will log out of the account.
LOGOUT_URL = 'logout'

# INTERNATIONALIZATION
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/dev/ref/settings/#language-code
LANGUAGE_CODE = 'en-us'

# Local time zone. Choices are
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# though not all of them may be available with every OS.
TIME_ZONE = 'UTC'

# https://docs.djangoproject.com/en/dev/ref/settings/#use-i18n
USE_I18N = True

# https://docs.djangoproject.com/en/dev/ref/settings/#use-l10n
USE_L10N = True

# https://docs.djangoproject.com/en/dev/ref/settings/#use-tz
USE_TZ = True


# MEDIA
# -----------------------------------------------------------------------------

# URL that handles the media served from MEDIA_ROOT, used for managing stored
# files. Read more at
# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-MEDIA_URL
MEDIA_URL = '/media/'

# DYNACONF
# -----------------------------------------------------------------------------

# HERE STARTS DYNACONF EXTENSION LOAD (Keep at the very bottom of base.py)
# Read more at https://www.dynaconf.com/#using-django
settings = dynaconf.DjangoDynaconf(
    __name__,
    ENVVAR_PREFIX_FOR_DYNACONF='BOOKMARKS',
    CORE_LOADERS=['TOML', 'PY'],
    ENV_SWITCHER_FOR_DYNACONF='BOOKMARKS_ENV',
    # Load this files in the order.
    SECRETS=['.secrets.toml'],
    settings_files=['development.toml', 'production.toml'],
)  # noqa
# HERE ENDS DYNACONF EXTENSION LOAD (No more code below this line)
