[production]
# General
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#debug
DEBUG = false

# https://docs.djangoproject.com/en/2.2/ref/settings/#allowed-hosts
ALLOWED_HOSTS = []


# Applications
# -----------------------------------------------------------------------------


# Databases
#------------------------------------------------------------------------------


# Static files (CSS, JavaScript, Images)
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '<your_path_to_static>'


# Media files
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#media-root
MEDIA_ROOT = '<your_path_to_static>'


# Email
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_BACKEND
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#https://docs.djangoproject.com/en/2.2/ref/settings/#email-timeout
EMAIL_TIMEOUT = 5
