# Generated by Django 2.2.17 on 2020-12-20 07:18

import bookmarks.apps.account.services
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default=bookmarks.apps.account.services.get_random_default_profile_photo, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\mkone\\PycharmProjects\\simple-social-network-django'), upload_to='media/users/%Y/%m/%d'),
        ),
    ]
